package com.demo.controllers;

import com.demo.services.BastionService;
import com.demo.services.EncryptionService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.websocket.server.PathParam;

/**
 * Created by johnb on 2/29/16.
 */
@Controller
public class KeyController {

    @Autowired
    private EncryptionService encryptionService;

    @Autowired
    private BastionService bastionService;

    @RequestMapping("/generatekey/{instanceId}")
    public String generateKey(@PathParam("instanceId") String instnaceId) throws Exception{

        //generate RSA SSH key to requested server
        encryptionService.generateKey("johnb");
        //Install public key to bastion and requested server
        bastionService.installKeys("johnb", "srprodbastion", "aws", "bastion.pem", 2200);
        //Create job to un-install key in 8 hours. Add entry to keys generated by who and from which IP address


        //Encrypt with Logged in user's key

        // Zip and send to user

        //Alert user key has been generated return to main page.

        return "generatekey";
    }



}
